FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./
COPY yarn.lock ./

# Install dependencies
RUN yarn install

# Expose port for development server
EXPOSE 3000

# Start development server
CMD ["yarn", "start"] 